/**
 * Scenario Composer archetypes (PRD Section 6, Feature 2).
 * Six pre-loaded fraud profiles with realistic TransactionParameters.
 */

import type { FraudArchetype, TransactionParameters } from "@/types";

/** Default parameters for "Custom Transaction" — neutral baseline for manual tuning. */
export const DEFAULT_PARAMETERS: TransactionParameters = {
  amount: 50000,
  hour: 12,
  dayOfWeek: 2,
  accountAgeDays: 365,
  senderCountry: "USA",
  receiverCountry: "Canada",
  transactionVelocity: 2,
  ipCountryMatchesSender: true,
  messageHasTypos: false,
  messageType: "pacs.008",
  isRoundNumber: false,
};

export const ARCHETYPES: FraudArchetype[] = [
  {
    id: "bec",
    name: "Business Email Compromise",
    description: "Corporate account redirected, large wire, new beneficiary",
    icon: "mail-warning",
    baseRiskLevel: "fraud",
    parameters: {
      amount: 187500,
      hour: 14,
      dayOfWeek: 1,
      accountAgeDays: 3,
      senderCountry: "USA",
      receiverCountry: "Nigeria",
      transactionVelocity: 8,
      ipCountryMatchesSender: false,
      messageHasTypos: true,
      messageType: "pacs.008",
      isRoundNumber: false,
    },
  },
  {
    id: "romance-scam",
    name: "Romance Scam",
    description: "Individual victim, repeated transfers, offshore destination",
    icon: "heart-crack",
    baseRiskLevel: "fraud",
    parameters: {
      amount: 45000,
      hour: 22,
      dayOfWeek: 6,
      accountAgeDays: 90,
      senderCountry: "UK",
      receiverCountry: "Cayman Islands",
      transactionVelocity: 5,
      ipCountryMatchesSender: true,
      messageHasTypos: true,
      messageType: "pacs.008",
      isRoundNumber: false,
    },
  },
  {
    id: "structuring",
    name: "Structuring / Smurfing",
    description: "Multiple sub-threshold transactions, same beneficiary",
    icon: "layers",
    baseRiskLevel: "suspicious",
    parameters: {
      amount: 9500,
      hour: 11,
      dayOfWeek: 2,
      accountAgeDays: 180,
      senderCountry: "USA",
      receiverCountry: "Panama",
      transactionVelocity: 15,
      ipCountryMatchesSender: true,
      messageHasTypos: false,
      messageType: "pacs.008",
      isRoundNumber: true,
    },
  },
  {
    id: "money-mule",
    name: "Money Mule Chain",
    description: "Rapid pass-through, multiple hops, mismatched countries",
    icon: "arrow-right-left",
    baseRiskLevel: "fraud",
    parameters: {
      amount: 75000,
      hour: 3,
      dayOfWeek: 4,
      accountAgeDays: 14,
      senderCountry: "Germany",
      receiverCountry: "Russia",
      transactionVelocity: 20,
      ipCountryMatchesSender: false,
      messageHasTypos: true,
      messageType: "pacs.009",
      isRoundNumber: true,
    },
  },
  {
    id: "corporate-payroll",
    name: "Corporate Payroll Run",
    description: "Batch, regular schedule, established accounts, domestic",
    icon: "building-2",
    baseRiskLevel: "clean",
    parameters: {
      amount: 250000,
      hour: 9,
      dayOfWeek: 1,
      accountAgeDays: 1500,
      senderCountry: "USA",
      receiverCountry: "USA",
      transactionVelocity: 1,
      ipCountryMatchesSender: true,
      messageHasTypos: false,
      messageType: "pacs.008",
      isRoundNumber: true,
    },
  },
  {
    id: "custom",
    name: "Custom Transaction",
    description: "Define all parameters manually",
    icon: "settings-2",
    baseRiskLevel: "unknown",
    parameters: DEFAULT_PARAMETERS,
  },
];
